<script lang="ts">
	import Game from '$lib/components/Game.svelte'

	const players = [
		{
			id: '1',
			name: 'Алексей',
			score: 1200,
			active: false,
			disconnected: false,
			pressedButton: null,
			answerAttemts: 5,
			ping: 45,
			partySubmitted: true,
			avatarUrl: undefined,
		},
		{
			id: '2',
			name: 'Мария',
			score: 800,
			active: false,
			disconnected: false,
			pressedButton: null,
			answerAttemts: 3,
			ping: 62,
			partySubmitted: true,
			avatarUrl: undefined,
		},
		{
			id: '3',
			name: 'Дмитрий',
			score: -200,
			active: false,
			disconnected: false,
			pressedButton: null,
			answerAttemts: 4,
			ping: 38,
			partySubmitted: true,
			avatarUrl: undefined,
		},
		{
			id: '4',
			name: 'Екатерина',
			score: 500,
			active: false,
			disconnected: false,
			pressedButton: null,
			answerAttemts: 2,
			ping: 55,
			partySubmitted: true,
			avatarUrl: undefined,
		},
		{
			id: '5',
			name: 'Игорь',
			score: 300,
			active: false,
			disconnected: false,
			pressedButton: null,
			answerAttemts: 1,
			ping: 70,
			partySubmitted: true,
			avatarUrl: undefined,
		},
		{
			id: '6',
			name: 'Ольга',
			score: 950,
			active: false,
			disconnected: false,
			pressedButton: null,
			answerAttemts: 6,
			ping: 41,
			partySubmitted: true,
			avatarUrl: undefined,
		},
	]
</script>

<Game
	state={{
		stage: {
			type: 'party-reveal',
			loading: false,
			price: 600,
			verdicts: [
				{
					playerName: 'Алексей',
					answer: 'Байкал',
					correct: true,
					scoreDiff: 300,
					confidenceBet: false,
					passed: false,
				},
				{
					playerName: 'Мария',
					answer: 'Каспийское море. На самом деле, оно очень большое и красивое',
					correct: false,
					scoreDiff: 0,
					confidenceBet: false,
					passed: false,
				},
				{
					playerName: 'Дмитрий',
					answer: '',
					correct: false,
					scoreDiff: 0,
					confidenceBet: false,
					passed: true,
				},
				{
					playerName: 'Екатерина',
					answer: 'Байкал',
					correct: true,
					scoreDiff: 600,
					confidenceBet: true,
					passed: false,
				},
				{
					playerName: 'Игорь',
					answer: 'Ладожское озеро',
					correct: false,
					scoreDiff: -600,
					confidenceBet: true,
					passed: false,
				},
				{
					playerName: 'Ольга',
					answer: '',
					correct: false,
					scoreDiff: 0,
					confidenceBet: false,
					passed: true,
				},
			],
		},
		players,
		disconnected: false,
		gameMode: 'party',
		controls: { mode: 'party-waiting' },
		stageBlink: false,
		showPlayers: true,
		messages: [],
	}}
	on:action={(e) => console.log('action', e.detail)}
/>
