name = "jeoshow-fe"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

pages_build_output_dir = ".svelte-kit/cloudflare"

[[r2_buckets]]
binding = "JEOSHOW_PACKS"
bucket_name = "jeoshow-packs"
