// Generated by Wrangler on Tue Mar 19 2024 18:52:50 GMT+0100 (Central European Standard Time)
// by running `wrangler types --env-interface CfEnv`

interface CfEnv {
	JEOSHOW_GAME_STATE: DurableObjectNamespace
	JEOSHOW_PACKS: R2Bucket
}
