// Generated by Wrangler on Mon Mar 18 2024 17:44:36 GMT+0100 (Central European Standard Time)
// by running `wrangler types --env-interface CfEnv`

interface CfEnv {
	JEOSHOW_GAME_STATE: DurableObjectNamespace;
}
