// Generated by Wrangler on Sat Mar 23 2024 21:56:05 GMT+0100 (Central European Standard Time)
// by running `wrangler types --env-interface CfEnv`

interface CfEnv {
	JEOSHOW_PACKS_METADATA: KVNamespace
	JEOSHOW_GAME_STATE: DurableObjectNamespace
	JEOSHOW_PACKS: R2Bucket
}
