name = "engine"
main = "src/index.ts"
compatibility_date = "2024-03-14"


[[durable_objects.bindings]]
name = "JEOSHOW_GAME_STATE"
class_name = "GameState"

[[migrations]]
tag = "v1"
new_classes = ["GameState"]
