name = "engine"
main = "src/entrypoint.ts"
compatibility_date = "2024-03-04"

tail_consumers = [{service = "tail-worker"}]

[[durable_objects.bindings]]
name = "JEOSHOW_GAME_STATE_SQLITE"
class_name = "GameDurableObjectSqlite"

[[migrations]]
tag = "v1"
new_classes = ["GameDurableObject"]

[[migrations]]
tag = "v2"
deleted_classes = ["GameDurableObject"]
new_sqlite_classes = ["GameDurableObjectSqlite"]


[[r2_buckets]]
binding = "JEOSHOW_PACKS"
bucket_name = "jeoshow-packs"

[[kv_namespaces]]
binding = "JEOSHOW_PACKS_METADATA"
id = "9f16fbbc252c4561a7e4ea0ceb611fb7"
