name = "engine"
main = "src/entrypoint.ts"
compatibility_date = "2024-03-04"
logpush = true

[[durable_objects.bindings]]
name = "JEOSHOW_GAME_STATE"
class_name = "GameDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["GameDurableObject"]


[[r2_buckets]]
binding = "JEOSHOW_PACKS"
bucket_name = "jeoshow-packs"

[[kv_namespaces]]
binding = "JEOSHOW_PACKS_METADATA"
id = "9f16fbbc252c4561a7e4ea0ceb611fb7"
