name = "engine"
main = "src/index.ts"
compatibility_date = "2024-03-04"


[[durable_objects.bindings]]
name = "JEOSHOW_GAME_STATE"
class_name = "GameDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["GameDurableObject"]


[[r2_buckets]]
binding = "JEOSHOW_PACKS"
bucket_name = "jeoshow-packs"
